// ECE:3350 SISC processor project
// status register

`timescale 1ns/100ps

module statreg (clk, in, stat_en, out);

  /*
   *  STATUS REGISTER - statreg.v
   *
   *  Inputs:
   *   - clk: System clock, positive edge active
   *   - in (4 bits): The status bits generated by the ALU. The status register
   *        saves these bits so that the control unit can use them in branches.
   *        For a description of the status bits, see the description of alu.v.
   *   - stat_en: When this is set to 1, the values of in are saved.
   *
   *  Outputs:
   *   - out (4 bits): The status bits saved from the ALU.
   *
   */

  input        clk;
  input  [3:0] in;
  input        stat_en;
  output [3:0] out;

  reg   [3:0] outreg;

  initial
    outreg = 4'b0000;
   
  always @ (posedge clk)
    if (stat_en == 1'b1)begin
      outreg = in;
	$display("SREG= %b", outreg);
	end
  assign out = outreg;

endmodule 
